// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sys} from '../models';
import {context} from '../models';

export function GetCPUUsage():Promise<sys.CPUUsage>;

export function OnStartup(arg1:context.Context):Promise<void>;
